### PR TITLE
Fixes #247 Fix Coordinated Omission

### LINKED ISSUE #247: The load generation need to fix Coordinated Omission
http://psy-lob-saw.blogspot.com/2016/07/fixing-co-in-cstress.html for some info about the approach taken

The `LocalWorker::submitProducersToExecutor` load generation isn't recording any "publish delay" computed by checking the actual send time vs the expected schedule.
A proper fix should fix both `endToEnd` and `publish` latencies using the intended send time vs the real one.

The reason why it's worths fixing this is that whatever prevent the load generation to work as expected should be recorded and weighted correctly to investigate the issue, otherwise inability to keep-up with the expected load will pass unnoticed in the percentiles ocean.

### PR DESCRIPTION
**Pull request by franz1981**
This is fixing Coordinated Omission by providing an additional metric ie `producer delay`: this metric should capture the delay while producing the load due to "some reason" (see https://github.com/openmessaging/benchmark/issues/247) preventing the generator to keep up with the expected configured rate.

This change is using a more appropriate rate limiter (different from the one of Guava) that's aware of the expected schedule.

The current strategy to find the sustainable rate (according to a specific backlog) is fine-ish to prevent it to happen, but actual measurements should be taken to check what happen during the actual test too.

### CODE REVIEW

**Comment by franz1981** [comment]
The latencies saved on `producer delay` are at microseconds granularity hence I didn't translated them in milliseconds as the other latencies, but probably this is going to impact whatever is used to report and read them.

**Comment by franz1981** [comment]
The sole problem with this implementation is if the rate is very low and there are many producers, changes in the rate won't unblock parked producers (awaiting their chance to fire): this could be fixed by implementing `uninterruptibleSleepNs` differently.

**Comment by franz1981** [comment]
Re a possible solution would be to use this `interruptibleSleepNs` instead:
```java
    private static final long MAX_SLEEP_NANOS = TimeUnit.MILLISECONDS.toNanos(100);

    public static <T> boolean interruptibleSleepNs(final long intendedTime, final T arg, final Predicate<? super T> isInterrupted) {
        long sleepNs;
        while ((sleepNs = (intendedTime - System.nanoTime())) > 0) {
            if (sleepNs < MAX_SLEEP_NANOS) {
                LockSupport.parkNanos(sleepNs);
            } else {
                LockSupport.parkNanos(MAX_SLEEP_NANOS);
                if (isInterrupted.test(arg)) {
                    return true;
                }
            }
        }
        return false;
    }
```
That should be used on `LocalWorker` as:
```java
    long intendedSendTime;
    while(true) {
        final UniformRateLimiter rateLimiter = this.rateLimiter;
        intendedSendTime = rateLimiter.acquire();
        if (!interruptibleSleepNs(intendedSendTime, rateLimiter, limiter -> limiter != this.rateLimiter)) {
            break;
        }
    }
```
It's a best effort method that keep on checking if the rate limiter has changed

**Comment by franz1981** [comment]
@dave2wave @codelipenghui @merlimat PTAL.

File: benchmark-framework/src/main/java/io/openmessaging/benchmark/TestResult.java [hunk 1]
```diff
@@ -45,6 +45,15 @@
     public List<Double> publishLatency9999pct = new ArrayList<>();
     public List<Double> publishLatencyMax = new ArrayList<>();
 
+    public List<Double> publishDelayLatencyAvg = new ArrayList<>();
```
Comment (merlimat) [inline benchmark-framework/src/main/java/io/openmessaging/benchmark/TestResult.java:48]: Does the publish delay only measures the delay we incur before calling `publish()` or the overall `delay + publish_latency` ?

**Review by merlimat — COMMENTED** [review]
Thanks @franz1981 for the great addition. I just have one clarification question.

File: benchmark-framework/src/main/java/io/openmessaging/benchmark/TestResult.java (hunk 1 above)
Comment (franz1981) [reply benchmark-framework/src/main/java/io/openmessaging/benchmark/TestResult.java:48]: The former; I've decided to just provide the delay (or "wait time", in queuing theory parlee) as an additional metrics to just verify sanity of the load generation process., without fixing both `publish` and `endToEnd` latencies.

TBH I'm opened to suggestions here and just for reference other load generators eg https://github.com/apache/cassandra/commit/89f275c6587150907b90ed03ca515b12c0c6ae11 have decided to "patch" the so-called service-time (ie `publish` and `endToEnd` without coordination omission adjustment) adding `wait time` (ie `publish_delay`) to it, turning it into a response-time ( = wait time + service time) when the appropriate test type is defined (fixed rate). 

I've chose a more relaxed approach, in order to save existing results to not be valid anymore :)

Comment (franz1981) [reply benchmark-framework/src/main/java/io/openmessaging/benchmark/TestResult.java:48]: @merlimat any further feedbacks on this?
I hope to try it soon with Kafka (that has a blocking client iirc) to show how it can be useful

Comment (dave2wave) [reply benchmark-framework/src/main/java/io/openmessaging/benchmark/TestResult.java:48]: If I understand this correctly this measure could be very helpful. For example, this measure could be used to help adjust the logic around finding the max production rate to be direct.

Comment (franz1981) [reply benchmark-framework/src/main/java/io/openmessaging/benchmark/TestResult.java:48]: > For example, this measure could be used to help adjust the logic around finding the max production rate to be direct.

Exactly or at least detect when there's something wrong that worth investigating:
- OS pause issues
- lack of CPU cycles because of AWS limitations
- client-side blocking behaviour(s)
- GC pauses
- ...

**Comment by franz1981** [comment]
@merlimat @vongosling there are any concern about this pr I can help clarify/address?

**Comment by vongosling** [comment]
@franz1981 nice, I'd like to your pr:-)

**Comment by franz1981** [comment]
Anyone got the chance to run it on real hw? @vongosling 
So i know i should add further changes mentioned on https://github.com/openmessaging/benchmark/pull/248#issuecomment-1055504200

**Comment by franz1981** [comment]
I've got the chance to run it on real hardware and it's working as expect, but if users define a too high rate, the producer delay keep on increasing reaching the boundaries defined for hdrhistogram latencies ie 1 minute, hence:

1. we can allow to gracefully handle it ie capturing the exception and stop producer(s)
2. just use an elastic hdr histogram recorder, that can grow to accomodate huge latency outliers

This won't be a problem in a proper set sustained rate, but could be bothersome while searching the expected rate.
Or, better we can use it to find the right sustainable rate as suggested by @dave2wave

**Comment by codelipenghui** [comment]
@franz1981 For the max throughput test, we always use `producerRate: 10000000` in workload files. With this change, we will see lots of logs like followings 

```
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]: java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: value outside of histogram covered range. Caused by: java.>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791) ~[?:?]
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) [?:?]
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.apache.pulsar.client.impl.ProducerImpl$1.sendComplete(ProducerImpl.java:389) [org.apache.pulsar-pulsar-client-all-2.11.0.jar:2.>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.apache.pulsar.client.impl.ProducerImpl$OpSendMsg.sendComplete(ProducerImpl.java:1465) [org.apache.pulsar-pulsar-client-all-2.11>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.apache.pulsar.client.impl.ProducerImpl.ackReceived(ProducerImpl.java:1167) [org.apache.pulsar-pulsar-client-all-2.11.0.jar:2.11>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.apache.pulsar.client.impl.ClientCnx.handleSendReceipt(ClientCnx.java:436) [org.apache.pulsar-pulsar-client-all-2.11.0.jar:2.11.>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:226) [org.apache.pulsar-pulsar-client-all-2.11.0.jar>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [o>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [o>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [org>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [org.apache.puls>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) [org.apache.puls>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) [org.apache.pulsar-pu>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [org.apache.pulsar-p>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [o>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [o>
lines 7657-7691
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) [org.apache.pulsar-pulsar-clien>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) [org.apache.pulsar-pulsar-client-all-2.1>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [org.apache.pu>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.apache.pulsar.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [org.apache.pulsar-pulsar-client->
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [org.apache.pulsar-pu>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at java.lang.Thread.run(Thread.java:833) [?:?]
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]: Caused by: java.lang.ArrayIndexOutOfBoundsException: value outside of histogram covered range. Caused by: java.lang.ArrayIndexOutOfBoundsExcep>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.HdrHistogram.AbstractHistogram.handleRecordException(AbstractHistogram.java:532) ~[org.hdrhistogram-HdrHistogram-2.1.10.jar:2.1>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.HdrHistogram.AbstractHistogram.recordSingleValue(AbstractHistogram.java:522) ~[org.hdrhistogram-HdrHistogram-2.1.10.jar:2.1.10]
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.HdrHistogram.AbstractHistogram.recordValue(AbstractHistogram.java:426) ~[org.hdrhistogram-HdrHistogram-2.1.10.jar:2.1.10]
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at org.HdrHistogram.Recorder.recordValue(Recorder.java:99) ~[org.hdrhistogram-HdrHistogram-2.1.10.jar:2.1.10]
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at io.openmessaging.benchmark.worker.LocalWorker.lambda$submitProducersToExecutor$8(LocalWorker.java:250) ~[io.openmessaging.benchmark>
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
Aug 08 15:03:46 ip-10-0-0-230.us-west-2.compute.internal benchmark-worker[28110]:         ... 32 more
```

I think we should consider avoiding adding values greater than 1min?

**Comment by franz1981** [comment]
@codelipenghui 

I see 2 good points here:
- it would be nice to not set any target rate for all out throughput tests
- use an expandable histogram to capture whatever high latencies will be hit if the load gen cannot keep up with the configured rate

Makes sense?

**Comment by codelipenghui** [comment]
@franz1981 

Make sense to me.
